@ProbabilityCalculator.Api_HostAddress = http://localhost:5288

###
POST {{ProbabilityCalculator.Api_HostAddress}}/api/v1.0/probability/calculate
Content-Type: application/json
Accept: application/json

{
  "parameter1": 0.5,
  "parameter2": 0.5,
  "functionName": "Either"
}
###
GET {{ProbabilityCalculator.Api_HostAddress}}/api/v1.0/probability/logs
Accept: application/json